/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.MenuPrincipal.common;

import ModuloAplicaciones.RegistrarAplicaciones;
import com.Login.common.Login;
import com.ModuloServidor.common.EliminarServidor;
import com.ModuloServidor.common.ModificarServidor;
import com.ModuloServidor.common.RegistrarServidor;
import com.ModuloUsuario.common.Eliminar;
import com.ModuloUsuario.common.Registrar;

/**
 *
 * @author Administrador
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    private String usuario="";
    
    public MenuPrincipal(String usuario) {
        initComponents();
        this.usuario=usuario;
        lblUsuario.setText("USUARIO: "+this.usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmInicio = new javax.swing.JMenu();
        jmiCerrar = new javax.swing.JMenuItem();
        jmUsuario = new javax.swing.JMenu();
        jmiRegistrar = new javax.swing.JMenuItem();
        jmiEliminar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        JmiRegistrarServ = new javax.swing.JCheckBoxMenuItem();
        JmiModificarServ = new javax.swing.JMenuItem();
        JmiEliminarServ = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JmenuIApps = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("JfMenuPrincipal"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setText("MENÚ PRINCIPAL.");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 150, 410, 49);

        lblUsuario.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText(" ");
        lblUsuario.setToolTipText("Usuario con sesión activa.");
        lblUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(190, 250, 210, 56);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MenuPrincipal/common/Bio-Grid_Computing.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 570, 370);

        jMenuBar1.setBackground(new java.awt.Color(102, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jmInicio.setForeground(new java.awt.Color(0, 0, 153));
        jmInicio.setText("INICIO");
        jmInicio.setToolTipText("Seleccione para ver las opciones del menú de Inicio.");
        jmInicio.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N

        jmiCerrar.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        jmiCerrar.setForeground(new java.awt.Color(0, 0, 153));
        jmiCerrar.setText("Cerrar Sesión");
        jmiCerrar.setToolTipText("Seleccione para cerrar la sesión del usuario.");
        jmiCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmiCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCerrarActionPerformed(evt);
            }
        });
        jmInicio.add(jmiCerrar);

        jMenuBar1.add(jmInicio);

        jmUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jmUsuario.setForeground(new java.awt.Color(0, 0, 153));
        jmUsuario.setText("USUARIOS");
        jmUsuario.setToolTipText("Seleccione para ver las opciones del menú de Usuarios.");
        jmUsuario.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N

        jmiRegistrar.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        jmiRegistrar.setForeground(new java.awt.Color(0, 0, 153));
        jmiRegistrar.setText("Registrar");
        jmiRegistrar.setToolTipText("Seleccione para registrar usuarios.");
        jmiRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmiRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistrarActionPerformed(evt);
            }
        });
        jmUsuario.add(jmiRegistrar);

        jmiEliminar.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        jmiEliminar.setForeground(new java.awt.Color(0, 0, 153));
        jmiEliminar.setText("Eliminar");
        jmiEliminar.setToolTipText("Seleccione para eliminar usuarios.");
        jmiEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmiEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEliminarActionPerformed(evt);
            }
        });
        jmUsuario.add(jmiEliminar);

        jMenuBar1.add(jmUsuario);

        jMenu1.setBackground(new java.awt.Color(0, 51, 153));
        jMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jMenu1.setForeground(new java.awt.Color(0, 0, 153));
        jMenu1.setText("SERVIDORES");
        jMenu1.setToolTipText("Seleccione para ver las opciones del menú de Servidores.");
        jMenu1.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N

        JmiRegistrarServ.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        JmiRegistrarServ.setForeground(new java.awt.Color(0, 0, 153));
        JmiRegistrarServ.setText("Registrar");
        JmiRegistrarServ.setToolTipText("Seleccione para registrar servidores.");
        JmiRegistrarServ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JmiRegistrarServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiRegistrarServActionPerformed(evt);
            }
        });
        jMenu1.add(JmiRegistrarServ);

        JmiModificarServ.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        JmiModificarServ.setForeground(new java.awt.Color(0, 0, 153));
        JmiModificarServ.setText("Modificar");
        JmiModificarServ.setToolTipText("Seleccione para modificar los servidores existentes.");
        JmiModificarServ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JmiModificarServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiModificarServActionPerformed(evt);
            }
        });
        jMenu1.add(JmiModificarServ);

        JmiEliminarServ.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        JmiEliminarServ.setForeground(new java.awt.Color(0, 0, 153));
        JmiEliminarServ.setText("Eliminar");
        JmiEliminarServ.setToolTipText("Seleccione para eliminar seridores.");
        JmiEliminarServ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JmiEliminarServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiEliminarServActionPerformed(evt);
            }
        });
        jMenu1.add(JmiEliminarServ);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Apps");

        JmenuIApps.setText("Registrar Apps");
        JmenuIApps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmenuIAppsActionPerformed(evt);
            }
        });
        jMenu2.add(JmenuIApps);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 587, 424);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Login JfLogin = new Login();
        JfLogin.show();
    }//GEN-LAST:event_formWindowClosed

    private void jmiRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegistrarActionPerformed
        Registrar jf_registrar = new Registrar("Principal");
        jf_registrar.show();
    }//GEN-LAST:event_jmiRegistrarActionPerformed

    private void jmiCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCerrarActionPerformed
        Login JfLogin = new Login();
       JfLogin.show();      
       this.dispose();
    }//GEN-LAST:event_jmiCerrarActionPerformed

    private void jmiEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEliminarActionPerformed
      Eliminar JframeEliminar = new  Eliminar(usuario);
      JframeEliminar.show();
    }//GEN-LAST:event_jmiEliminarActionPerformed

    private void JmiRegistrarServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiRegistrarServActionPerformed

         RegistrarServidor JfModuloServidor = new RegistrarServidor();
        JfModuloServidor.show();
    }//GEN-LAST:event_JmiRegistrarServActionPerformed

    private void JmiModificarServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiModificarServActionPerformed
        
         ModificarServidor JfModificarServ = new ModificarServidor();
        JfModificarServ.show();
    }//GEN-LAST:event_JmiModificarServActionPerformed

    private void JmiEliminarServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiEliminarServActionPerformed
        EliminarServidor JfEliminarServ = new EliminarServidor();
        JfEliminarServ.show();
    }//GEN-LAST:event_JmiEliminarServActionPerformed

    private void JmenuIAppsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmenuIAppsActionPerformed
      RegistrarAplicaciones apps= new RegistrarAplicaciones();
      apps.show();
    }//GEN-LAST:event_JmenuIAppsActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JmenuIApps;
    private javax.swing.JMenuItem JmiEliminarServ;
    private javax.swing.JMenuItem JmiModificarServ;
    private javax.swing.JCheckBoxMenuItem JmiRegistrarServ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmInicio;
    private javax.swing.JMenu jmUsuario;
    private javax.swing.JMenuItem jmiCerrar;
    private javax.swing.JMenuItem jmiEliminar;
    private javax.swing.JMenuItem jmiRegistrar;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
